remote_theme: just-the-docs/just-the-docs

title: Drupal Unit Testing
description: An introduction and overview of Drupal unit testing.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://akempler.github.io/drupal_phpunit/" # the base hostname & protocol for your site, e.g. http://example.com

# Enable or disable heading anchors
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/akempler/drupal_phpunit" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
